//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_tips
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int id_cl { get; set; }
        public string num_cl { get; set; }
        public string nom_cl { get; set; }
        public string prenom_cl { get; set; }
        public string ville { get; set; }
        public Nullable<int> age { get; set; }
    }
}
